using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Common {
    public enum ComponentID : int {
        Model,
        Damagable,
        Character,
        Properties,
        Transform,
        Activator,
        PlayerAI,
        Asteroid,
        CombatAI,
        Bot,
        Ship,
        Chest,
        EventedObject,
        PropertyUpdater,
        MmoMessager,
        PirateStation,
        Planet,
        Bonuses,
        PlayerLoader,
        Skills,
        Target,
        Raceable,
        Energy,
        Weapon,
        Event,
        Player,
        Movable,
        Outpost,
        Respawnable,
        NebulaObject,
        Turret,
        MainOutpost,
        SharedChest,
        Teleport,
        SubZone,
        Station,
        Skill_7DB,
        Skill_45E,
        DatabaseObject,
        PassiveBonuses,
        MiningStation,
        PvpStore,
        PlayerTimedEffects,
        PetObject,
        PetManager,
        DropList,
        FounderCube,
        EventSubscriber,
        ContractManager,
        ContractObject = 49,
        ContractMark = 50,
        Trigger = 51,
        Achievments = 52,
        PlanetBuilding = 53,
        LoreBox = 54,
        PlanetBasedObject = 55
    }
}
