namespace Nebula.Server.Components {
    public enum ComponentSubType : int {
        player_ship_movable,
        bot_ship_movable,
        simple_movable,
        ai_orbit,
        ai_patrol,
        ai_stay,
        ai_wander_point,
        ai_wander_cube,
        ai_follow_path_combat,
        ai_follow_path_non_combat,
        damagable_not_ship,
        damagable_ship,
        damagable_fixed_damage,
        damagable_outpost,
        character_bot,
        character_player,
        ship_bot,
        weapon_ship,
        weapon_simple,
        spawn_pirate_activator,
        simple_model,
        raceable_model,
        SimpleTeleport,
        PersonalTeleport,
        kill_npc_group_contract_mark
    }
}
