using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Common {
    public enum LogicErrorCode : int {
        OK = 0,
        GROUP_ACTION_REQUEST_IS_NULL = 1,
        PLAYER_NOT_HAS_GROUP_ACTION_REQUEST = 2,
        GROUP_REQUEST_RESPONSE_ALREADY_RECEIVED = 3,
        RESPONSE_AND_REQUEST_TYPES_DONT_SAME = 4,
        PLAYER_DONT_ACCEPT_GROUP_REQUEST = 5,
        ITEM_NOT_FOUND = 6,
        SOURCE_GROUP_IS_NULL = 7,
        GROUP_IS_FULL = 8,
        ERROR_OF_EXITING_FROM_GROUP = 9,
        GROUP_MEMBER_NOT_FOUND = 10,
        PLAYER_ALREADY_HAS_NOT_HANDLED_REQUEST = 11,
        ITEM_NULL_OR_DISPOSED = 12,
        PLAYER_ALREADY_ATTACHED_TO_SOME_GROUP = 13,
        CURRENT_GROUP_IS_NULL = 14,
        MEMBER_IS_NOT_LEADER = 15,
        TARGET_MEMBER_NOT_FOUNDED = 16,
        I_AM_ALREDY_LEADER = 17,
        EXCLUDE_VOTE_DONT_ALLOW_WHEN_TWO_MEMBERS = 18,
        EXCLUDE_VOTE_FOR_SELF_DONT_ALLOWED = 19,
        ALREADY_EXISTS_EXCLUDE_REQUEST = 20,
        NO_EXCLUDE_REQUEST_IN_GROUP = 21,
        GROUP_NOT_FOUNDED = 22
    }
}
