namespace NebulaCommon {
    public enum ServerToServerParameterCode : byte {
        UdpPort = 1,
        TcpPort = 2,
        ServerId = 3,
        GameServerAddress = 4,
        WebSocketPort = 6,
        ServerState = 7,
        AuthList = 8,
        ExternalAddress = 9,
        InternalAddress = 10,
        SharedKey = 11,
        GameRefId = 12,
        CharacterId = 13,
        SlotType = 14,
        TemplateId = 15,
        ServerType = 16,
        Level = 17,
        Workshop = 18,
        Exp = 19,
        Race = 20,
        Alive = 21,
        Model = 22,
        Group = 23,
        WorldId = 24,
        ID = 25,
        InventoryType = 26,
        Count = 27,
        TransactionID = 28,
        TransactionSource = 29,
        Success = 30,
        Result = 31,
        ReturnCode = 32,
        Action = 33,
        SourceServer,
        TargetServer,
        Method,
        Arguments,
        Tag,
        TargetObject,
        RaceStatus,
        Items,
        PreviousRace,
        CurrentRace
    }
}
