using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ServerClientCommon {

    /// <summary>
    /// Sub parameter code
    /// </summary>
    public enum SPC : int {
        ServerType          = 1,
        IpAddress           = 2,
        Protocol            = 3,
        Port                = 4,
        Index               = 5,
        Id                  = 6,
        Name                = 7,
        Level               = 8,
        Workshop            = 9,
        Deleted             = 10,
        Race                = 11,
        Exp                 = 12,
        Model               = 13,
        Group               = 14,
        GameRefId           = 15,
        DisplayName         = 16,
        SelectedCharacterId = 17,
        Characters          = 18,
        Count               = 19,
        Info                = 20,
        SlotsUsed = 21,
        MaxSlots = 22,
        Items = 23,
        ItemType = 24,
        Template = 25,
        NumSlots = 26,
        ProductionSpeed = 27,
        ProtectionInterval = 28,
        Health = 29,
        MaterialType = 30,
        Color = 31,
        CraftMaterials = 32,
        //HeavyShotInfo = 33,
        //LightShotInfo = 34,
        OptimalDistance = 35,
        Range = 36,
        CritChance = 37,
        DamageType = 38,
        MultiCount = 39,
        HasSkill = 40,
        UseTime = 41,
        IsOn = 42,
        Timer = 43,
        Cooldown = 44,
        SkillType = 45,
        Hold = 46,
        Inventory = 47,
        Type = 48,
        Set = 49,
        Speed = 50,
        Resist = 51,
        DamageBonus = 52,
        DistanceBonus = 53,
        Skill = 54,
        HoldType = 55,
        Energy = 56,
        EnergyRestoration = 57,
        Difficulty = 58,
        Prefab = 59,
        CritDamage = 60,
        HasWeapon = 61,
        //LightReady = 62,
        //HeavyReady=63,
        //HeavyCooldown = 64,
        //LightCooldown = 65,
        HitProb = 66,
        //LightTimer = 67,
        //HeavyTimer = 68,
        Source = 69,
        //HeavyDamage = 70,
        //LightDamage = 71,
        Damage = 72,
        ContainerId = 73,
        ContainerType = 74,
        ContainerItemId = 75,
        ContainerItemType = 76,
        ErrorMessageId = 77,
        IsGod = 78,
        SpecificInfo = 79,
        VarStageTimer = 80,
        VarPiratesKilled,
        VarSecurityKilled,
        VarStationsDestroyed,
        VarBossKilled,
        WorldId,
        Variables,
        VarKilledCounter,
        VarDataCollected,
        VarCollectedOre0001,
        VarCollectedOre0002,
        VarCollectedOre0003,
        VarCollectedOre0004,
        VarCollectedOre0005,
        VarCollectedOre0006,
        VarKillWave1,
        VarKillWave2,
        VarKillWave3,
        VarKillWave4,
        VarKillWave5,
        VarKillCounter1,
        VarKillCounter2,
        Description,
        Credits,
        Active,
        Inputs,
        Position,
        CurrentStage,
        Members,
        Opened,
        ChatMessageGroup,
        ChatMessage,
        ChatSourceLogin,
        ChatMessageSourceName,
        ChatMessageId,
        ChatReceiverLogin,
        ChatSourceName,
        IsLeader,
        Buffs,
        ItemId,
        RequestType,
        Data,
        FromCharacterId,
        FromDisplayName,
        ToExcludeCharacterId,
        ToExcludeDisplayName,
        //TargetId,
        TargetType,
        IsHitted,
        ActualDamage,
        OverheatingGuns,
        FireBlocked,
        FireAllowed,
        IsCritical,
        //ShotType,
        Message,
        SourceType,
        Target,
        ChatMessageTime,
        OwnedRace,
        ZoneInfo,
        StageId,
        StartText,
        TaskText,
        IsFinal,
        IsSuccess,
        Timeout,
        AttachedObject,
        Mails,
        SenderId, 
        SenderType,
        ReceiverId,
        ReceiverType,
        Title,
        Body,
        Attachments,
        Readed,
        Time,
        SenderName,
        ReceiverName,
        RequireWeaponSlot,
        Duration,
        SlotType,
        Radius,
        Action,
        InitialOwnedRace,
        ZoneType,
        SlotCount,
        Tag,
        CollectedContent,
        Application,
        MaxHealth,
        Destroyed,
        LastFireTime,
        Ready,
        FarProb,
        NearProb,
        FarDist,
        NearDist,
        MaxHitSpeed,
        MaxFireDistance,
        CurHealth,
        Locations,
        Content,
        PlacingType,
        RespondAction,
        SourceServiceType,
        Text,
        Handled,
        CharacterId,
        Notifications,
        Login,
        Status,
        GuildRating,
        Guild,
        Price,
        ObjectType,
        EnergyBonus,
        SpeedBonus,
        HoldBonus,
        StartRace,
        CurrentRace,
        WorldType,
        UnderAttack,
        AttackRace,
        RaceStatus,
        Distance,
        ReturnCode,
        PlayerCount,
        ShotID,
        MinPrice,
        MaxPrice,
        MinLevel,
        MaxLevel,
        SubType,
        ControlState,
        HealValue,
        ModerCount,
        MaxModerCount,
        CharacterName,
        Points,
        Voices,
        RegistrationStartTime,
        VoteStartTime,
        VoteEndTime,
        VotingStarted,
        RegistrationStarted,
        CurrentTime,
        SourceGameRefID,
        TargetGameRefID,
        SourceLogin,
        TargetLogin,
        Binded,
        Interval,
        Value,
        Capacity,
        MoneyType,
        Lang,
        PostURL,
        ImageURL,
        IgnoreDamagaeAtStart,
        IgnoreDamageInterval,
        CreateChestOnKilling,
        FixedInputDamage,
        AdditionalHp,
        Fraction,
        Badge,
        Size,
        SubZoneID,
        UseTargetHpForDamage,
        TargetHpPercentDamage,
        AlignWithForwardDirection,
        RotationSpeed,
        UseHitProbForAgro,
        AttackMovingType,
        Splittable,
        Tier,
        LearningStarted,
        LearnStartTime,
        LearnEndTime,
        LearnProgress,
        Free,
        AssignedStationID,
        AssignedStationType,
        AssignedStationRace,
        PlanetSlots,
        MiningStationOwnedPlayer,
        NebulaElementId,
        MaxCount,
        WarnCount,
        MaxWarnCount,
        PreviousRace
    }
}
